### ISSUE TITLE
Update Mockups Based on feedback given on Nov. 7th

### ISSUE THREAD

**Issue by NicholasNagy** [Fruity-Loops/ALTA#153]
We need to address the notes on figma as well as some extra notes here:

**Inventory Manager:**

- [x] When initiating an audit, user has the choice between those two options: 1) From a predefined template 2) Go to inventory items section

- [x] Once the audit is created, it brings the user back to a 'summary' page where user is able to assign the newly created audit to a stock-keeper.

- [x] This is done at the location level for now (?) ...

- [x] ... but should be able to do multiple assign to stock keepers at different location (implemented as a drag drop to be more intuitive?)

**Stock-keeper:**

- [x] Have only 1 tab for audited items 

- [x] Color code the items found in a list from the above tab [green for validated, yellow for newly found, and red for missing/unvalidated items, maybe add a small icon as well

**Comment by daphneaugier** [comment]
**Regarding the stock-keeper** : 
Now we have 2 tabs : one for items and one for completed items
Added a circle that color codes the items : green -> VALID, yellow -> NEW and red -> MISSING
Instead of having the whole rectangle being colored I think that having just a circle is lighter and more agréable à l'oeil.

<img width="412" alt="Capture d’écran 2020-11-16 à 20 37 22" src="https://user-images.githubusercontent.com/35980232/99299468-8a20dd80-284b-11eb-9a47-665b6cdfcd46.png">

**Comment by daphneaugier** [comment]
**For inventory manager :**
This is the page where you can assign the stock keepers from different locations

<img width="674" alt="Capture d’écran 2020-11-17 à 15 08 40" src="https://user-images.githubusercontent.com/35980232/99400037-c7867900-28e6-11eb-9ee8-69687384fae7.png">
